[package]
name = "folder_maid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "*"
crossbeam-channel = "0.4.0"
watchman_client = "0.7.1"
notify = "4.0.17"
structopt = "0.3.26"
